"""empty message

Revision ID: 6b62222be836
Revises: 
Create Date: 2020-08-19 04:01:12.922112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b62222be836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('vaccination',
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('drug', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['drug'], ['drug.code'], ),
    sa.PrimaryKeyConstraint('rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination')
    op.drop_table('drug')
    # ### end Alembic commands ###
